name       : mate-desktop
version    : 1.24.1
release    : 23
source     :
    - https://github.com/mate-desktop/mate-desktop/archive/v1.24.1.tar.gz : 063002ef830640d5985dba66454fe826348ccfd0c599f18484ba5a03d926a29c
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - GFDL-1.1-or-later
component  : desktop.mate
homepage   : https://mate-desktop.org/
summary    : Core library for MATE Desktop applications
description: |
    mate-desktop contains the libmate-desktop library, the mate-about program as well as some desktop-wide documents.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(x11)
    - mate-common
setup      : |
    %autogen --disable-static \
             --enable-gtk-doc \
             --with-pnp-ids-path=/usr/share/hwdata/pnp.ids
build      : |
    %make
install    : |
    %make_install
