name       : mate-desktop
version    : 1.14.1
release    : 1
source     :
    - http://pub.mate-desktop.org/releases/1.14/mate-desktop-1.14.1.tar.xz : 97b5067c3b9a0b96494cf189dc94e64ac852cd21cddc27961e7b744f550d5786
license    :
    - GPL-2.0
    - LGPL-2.0
    - GFDL-1.1
component  : desktop.mate
summary    : Core library for MATE Desktop applications
description: |
    mate-desktop contains the libmate-desktop library, the mate-about program as well as some desktop-wide documents.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(x11)
setup      : |
    %configure --disable-static --with-gtk=3.0 --with-x
build      : |
    %make
install    : |
    %make_install
