name       : mate-desktop
version    : 1.20.0
release    : 9
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-desktop-1.20.0.tar.xz : 36d0722750ce30ba8d4b8b735bef6ad1b1b4c8f9f51257e36ec419b9b438a178
license    :
    - GPL-2.0
    - LGPL-2.0
    - GFDL-1.1
component  : desktop.mate
summary    : Core library for MATE Desktop applications
description: |
    mate-desktop contains the libmate-desktop library, the mate-about program as well as some desktop-wide documents.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(x11)
    - mate-common
setup      : |
    %reconfigure --disable-static \
                 --with-x \
                 --with-pnp-ids-path=/usr/share/hwdata/pnp.ids
build      : |
    %make
install    : |
    %make_install
