name       : mate-desktop
version    : 1.16.0
release    : 2
source     :
    - http://pub.mate-desktop.org/releases/1.16/mate-desktop-1.16.0.tar.xz : 568d0b4aff4a02e3eaa19a679554487f21899dd3acb0d59da4d5f9879050d1bb
license    :
    - GPL-2.0
    - LGPL-2.0
    - GFDL-1.1
component  : desktop.mate
summary    : Core library for MATE Desktop applications
description: |
    mate-desktop contains the libmate-desktop library, the mate-about program as well as some desktop-wide documents.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(x11)
setup      : |
    %configure --disable-static --with-gtk=3.0 --with-x
build      : |
    %make
install    : |
    %make_install
