name       : mate-desktop
version    : 1.27.1
release    : 30
source     :
    - https://github.com/mate-desktop/mate-desktop/releases/download/v1.27.1/mate-desktop-1.27.1.tar.xz : eb194b0525c2b49b22f44e767d38ababa2139bf9caa7dc209e6f93abd76364ea
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - GFDL-1.1-or-later
component  : desktop.mate
homepage   : https://mate-desktop.org/
summary    : Core library for MATE Desktop applications
description: |
    mate-desktop contains the libmate-desktop library, the mate-about program as well as some desktop-wide documents.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(x11)
    - mate-common
setup      : |
    %configure --disable-static \
               --enable-gtk-doc \
               --with-pnp-ids-path=/usr/share/hwdata/pnp.ids
build      : |
    %make
install    : |
    %make_install
