name       : mate-desktop
version    : 1.6.1
release    : 4
source     :
    - http://pub.mate-desktop.org/releases/1.16/mate-desktop-1.16.1.tar.xz : 587a8da6e65386015101992e1082bb4d4d38420873c70348ba55dc9f9f63f6df
license    :
    - GPL-2.0
    - LGPL-2.0
    - GFDL-1.1
component  : desktop.mate
summary    : Core library for MATE Desktop applications
description: |
    mate-desktop contains the libmate-desktop library, the mate-about program as well as some desktop-wide documents.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(x11)
setup      : |
    %configure --disable-static --with-gtk=3.0 --with-x
build      : |
    %make
install    : |
    %make_install
