name       : mate-desktop
version    : 1.20.4
release    : 14
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-desktop-1.20.4.tar.xz : b9bbb086c352764a6bf01a3c792a2858336b3a28a82ffb818b509de290b1701c
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - GFDL-1.1-only
component  : desktop.mate
summary    : Core library for MATE Desktop applications
description: |
    mate-desktop contains the libmate-desktop library, the mate-about program as well as some desktop-wide documents.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(x11)
    - mate-common
rundeps    :
    - ccsm
setup      : |
    %reconfigure --disable-static \
                 --with-x \
                 --with-pnp-ids-path=/usr/share/hwdata/pnp.ids
build      : |
    %make
install    : |
    %make_install
