name       : mate-desktop
version    : 1.18.0
release    : 8
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-desktop-1.18.0.tar.xz : 6f2dd9fc60bacd0ff27b8328c7addceb9e73a75c7dce7db4132659d588173b8a
license    :
    - GPL-2.0
    - LGPL-2.0
    - GFDL-1.1
component  : desktop.mate
summary    : Core library for MATE Desktop applications
description: |
    mate-desktop contains the libmate-desktop library, the mate-about program as well as some desktop-wide documents.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(x11)
    - mate-common
setup      : |
    %patch -p1 < $pkgfiles/global-menu-support.patch
    %reconfigure --disable-static \
                 --with-x \
                 --with-pnp-ids-path=/usr/share/hwdata/pnp.ids
build      : |
    %make
install    : |
    %make_install
