name       : mate-desktop
version    : 1.20.3
release    : 12
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-desktop-1.20.3.tar.xz : da395f4f640e8b26d6704a5d63e00eeea0393f343cf5f92e2b211458390f5f8c
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - GFDL-1.1-only
component  : desktop.mate
summary    : Core library for MATE Desktop applications
description: |
    mate-desktop contains the libmate-desktop library, the mate-about program as well as some desktop-wide documents.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(x11)
    - mate-common
setup      : |
    %reconfigure --disable-static \
                 --with-x \
                 --with-pnp-ids-path=/usr/share/hwdata/pnp.ids
build      : |
    %make
install    : |
    %make_install
